---
title: "Playground for geocoder"
author: "Hayley Boyce"
date: "10/04/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(taxyvr)
library(stringr)
tax_2019
```

```{r}
coords <- read_csv2("property-addresses.csv")
coords
```

```{r}
new <- coords

new <- new %>% mutate(PCOORD = as.numeric(PCOORD))
new
```

```{r}
tax_2019 %>% left_join(new, by = c("to_civic_number" = "CIVIC_NUMBER", "street_name" = "street_name") )
```

```{r}
tax_2019$pid <- gsub("-", "", tax_2019$pid)
combo <- tax_2019 %>% left_join(new, by = c("land_coordinate" = "PCOORD") )

```

```{r}
combo %>% group_by(folio) %>% slice(1) %>% filter(is.na(Geom))
```


# Full code if want coordinates 

```{r}

# Get latitude and logitude database

#coords <- read_csv2("property-addresses.csv")

coords <-
  read_csv2(
    "https://opendata.vancouver.ca/explore/dataset/property-addresses/download/?format=csv&timezone=America/Los_Angeles&lang=en&use_labels_for_header=true&csv_separator=%3B"
  )

# Convert PCOORD to correct type 
coords <- coords %>% mutate(PCOORD = as.numeric(PCOORD))

# join with tax dataframe 
combo <- tax_2019 %>% left_join(coords, by = c("land_coordinate" = "PCOORD") )

#remove duplicates of folio that are created when joined with coord df
ll_df <- combo %>% group_by(folio) %>% slice(1) 
ll_df
```



```{r}

# obtain the latitude and longitude of the column (tried replace and gsub without success)
ll_df <- ll_df %>% separate(Geom, c("junk","needed"), sep = "\\[") 
ll_df <- ll_df %>% separate(needed, c("needed2","morejunk"), sep = "\\]") 
ll_df <- ll_df %>% separate(needed2, c("longitude","latitude"), sep = "\\,")

ll_df  <- ll_df %>%  select(-junk, -morejunk, -STD_STREET) %>% mutate(longitude = as.numeric(longitude), latitude = as.numeric(latitude))
ll_df
```



```{r}
ll_df$full_address <- paste(ll_df$to_civic_number, 
                            " ",
                            ll_df$street_name,
                            ", Vancouver, BC, ",
                            ll_df$property_postal_code,
                            sep="")
ll_df
```

```{R}
library(ggmap)
#citation("ggmap")
x =geocode("4888 BELMONT AVE, Vancouver, BC, V6T 1A9", output = "latlona", source = "google")
```

```{r}
missing = ll_df %>% filter(is.na(latitude))
```



```{r}
new_coords <-  geocode(missing$full_address,output = "latlona", source = "google")
new_coords_xtra_a <- new_coords %>%
                      cbind(full_address = missing$full_address)
```




```{r}
second_ll <- ll_df %>% left_join(new_coords_xtra_a, by="full_address")
second_ll <- second_ll %>% 
             mutate(latitude = ifelse(is.na(latitude), lat, latitude),
                    longitude = ifelse(is.na(longitude), lon, longitude)) %>% 
            select(-lat, -lon, -address, -full_address, -CIVIC_NUMBER, -P_PARCEL_ID, -SITE_ID) %>% rename(geo_local_area=`Geo Local Area`)

second_ll %>% filter(is.na(longitude))
```



```{r}
API_KEY= ""

register_google(key = API_KEY)
```

```{r}
ll_df %>% mu
browseVignettes("taxyvr")
```

```{R}
addresses <-  get(load(file = "data/addresses.rda"))
```

